### ISSUE TITLE
Failed to activate the git-diff-popup package

### ISSUE THREAD

**Issue by tomwganem** [mark-hahn/git-diff-popup#2]
[Enter steps to reproduce below:]
1. enable package

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [git-diff-popup](https://github.com/mark-hahn/git-diff-popup) package, v0.1.2
### Stack Trace

Failed to activate the git-diff-popup package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/tomwganem/.atom/packages/git-diff-popup/lib/git-diff-popup.coffee:11:37)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:303:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:132:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:213:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```
### Commands

```
     -3:52.4.0 core:select-all (atom-text-editor.editor)
     -3:51.7.0 core:copy (atom-text-editor.editor)
     -3:46 git-diff:move-to-next-diff (atom-text-editor.editor)
     -2:53.9.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "vim-mode",
      "git-plus",
      "Zen",
      "git-difftool",
      "tabular",
      "autoclose-html",
      "atom-ctags",
      "minimap-color-highlight",
      "terminal-panel",
      "regex-railroad-diagram",
      "git-show"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
autocomplete-ruby, v0.1.0
editor-stats, v0.17.0
git-diff-popup, v0.1.2
language-jade, v0.4.0
last-cursor-position, v0.8.0
linter, v0.12.1
linter-ruby, v0.1.4
minimap, v4.7.6
minimap-git-diff, v4.1.2
monokai, v0.14.0
ruby-block, v0.3.3
todo-show, v0.8.0

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
Thanks for the report.

Fixed in 0.1.3
