### ISSUE TITLE
Git diff popup error.

### ISSUE THREAD

**Issue by lokeshjainRL** [mark-hahn/git-diff-popup#6]
I am using mac with latest os. 
getting following error.

`The selection does not overlap a git difference.`

Am i missing something on how to use? help me i need this plugin working. 

```

/Users/Lokesh/.atom/packages/git-diff-popup/lib/diff.coffee:124
Hide Stack Trace
TypeError: Cannot read property 'left' of undefined
  at Diff.module.exports.Diff.getDiffBox (/Users/Lokesh/.atom/packages/git-diff-popup/lib/diff.coffee:124:11)
  at PopupView.module.exports.PopupView.setViewPosDim (/Users/Lokesh/.atom/packages/git-diff-popup/lib/popup-view.coffee:86:52)
  at /Users/Lokesh/.atom/packages/git-diff-popup/lib/popup-view.coffee:32:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

**Comment by mark-hahn** [comment]
Is this on one particular file?  Are you sure the selected text is in a git
diff line?

If you can, point me to the repo and tell me the file you ran it on and
where you clicked.  I'll check out the file from the repo and test it.
